# Generated by Django 4.2.1 on 2023-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_cariation_value_variation_variation_value'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartiteam',
            name='variation',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
