# Generated by Django 4.2.1 on 2023-06-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartiteam_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartiteam',
            old_name='variation',
            new_name='variations',
        ),
    ]
